# -*- coding: utf-8 -*-
"""LabPA_3_Sg2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1O__GVFh-ZnjUjIOFffY0gdGMMhBwp5oP

Exercitiul 1
"""

# 1a si b
L=[chr(x) for x in range (ord('a'),ord('z')+1)]
lista=[x for x in range (10) if x%2==1]
print(lista)
print(L)

# 1c
n=4
listac=[x if x%2==1 else -x for x in range(1,n+1)]
print(listac)

#1d
def newlist(L):
    l = [x for x in L if x%2==1]
    return l

print(newlist([1,2,3,79,5,6]))

#1e
def pct_e(L):
    l = [L[i] for i in range(len(L)) if i%2 == 1]
    return l

print(pct_e([1,2,3,79,5,6]))
#1f
def pct_f(L):
    l=[L[i] for i in range (len(L)) if L[i]%2==i%2]
    return l
print(pct_f([2,4,1,7,5,1,8,10]))


#1g
def pct_g(L):
    l = [(L[i], L[i+1]) for i in range(len(L) - 1)]
    return l

print(pct_g([2,4,1,7,5,1,8,10]))

def pct_h(n):
    L=[[f'{x}*{y}={x*y}' for y in range(1, n+1)] for x in range (1, n+1)]
    return L
L = pct_h(5)
print(L)

def pct_i(n):
    L=[[x]*x for x in range(n)]
    return L
print(pct_i(5))

"""Exercitiul 2"""

L=[1,12,13,56,27,111]
L.sort(key=lambda x: str (x))
print(L)
L.sort(key=lambda x: str (x)[::-1])
print(L)
L.sort(key=lambda x: len(str(abs(x))))
print(L)
L.sort(key=lambda x: len(set(str(abs(x)))))
print(L)

"""Exercitiul 3"""

from string import punctuation

with open("propo.txt") as f:
    s=f.readline()
    d={}
    for cuvant in s.split():
        cuvant=cuvant.strip(punctuation).lower()
        d[cuvant]=d.get(cuvant,0)+1
    sorted_dict = sorted([(val, key) for key, val in d.items()])
    print(sorted_dict[0][1])
    # i = len(sorted_dict) - 1
    for i in range(len(sorted_dict) - 1,0,-1):
        if sorted_dict[i-1][0]!=sorted_dict[i][0]:
            break
    print(sorted_dict[i][1])















