# -*- coding: utf-8 -*-
"""LabPA_2_Sg1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VyFJz9N9Yl1vpWc5MEC63A-iauAGyEQW

Problema 1
"""

# Problema 1

propozitie = input("Introduceti propozitia:\n")
greseala = input("Greseala:\n")
corectare = input("Forma corecta:\n")

propozitie = propozitie.replace(greseala,corectare)
print(propozitie)

"""Problema 2"""

# Problema 2

sir_initial = input("Introduceti sirul initial")
sir_initial = sir_initial.title()

print(sir_initial)

"""Problema 3"""

# Problema 3

propozitie = input("Propozitie:\n")
sir1 = input("Sir 1:\n")
sir2 = input("Sir 2:\n")

propozitie_modificata = " " + propozitie + " "
lista = propozitie_modificata.find(sir1)

last_idx = 0
find_idx = 0
aux = []

while propozitie_modificata.find(sir1, find_idx) != -1:
    i = propozitie_modificata.find(sir1, find_idx)
    if not propozitie_modificata[i - 1].isalpha() and not propozitie_modificata[i + len(sir1)].isalpha():
        aux.append(propozitie_modificata[last_idx:i])
        last_idx = i + len(sir1)
    find_idx = i + len(sir1)
aux.append(propozitie_modificata[last_idx:])

final = sir2.join(aux)[1:-1] if len(aux) > 0 else propozitie
print(final)

# Problema 3 - Varianta 2

sir = input("Introduceti sirul initial ")
cuvant_inlocuit = input("Cuvant inlocuit ")
cuvant_inserat = input("Cuvant inserat ")

sir = sir + ' '

lungime = len(cuvant_inlocuit)

index = sir.find(cuvant_inlocuit)
if index == 0 and sir[lungime].isalpha() == 0:
    sir = cuvant_inserat + sir[lungime:]
    index = sir.find(cuvant_inlocuit , index + 1)

while index != -1:
    if sir[index-1].isalpha()  == 0 and sir[index + lungime].isalpha() == 0:
        sir = sir[:index] + cuvant_inserat + sir[index + lungime:]
    index = sir.find(cuvant_inlocuit, index + 1)

print(sir)

# Problema 3 - varianta cu regex

import re

text = input("Text = ")
find = input("Find = ")
replace = input("Replace = ")
punctuation = ",.!?<>;:'\""
regex = f"([{punctuation}])"
words = re.split(regex, text)
answer = ''.join([replace if word == find else word for word in words])
print(answer)

"""Cautare binara in Python"""

# cautare binara
L = map(int, input().split())
x = input("Numarul cautat este: ")
st, dr = 0, len(L) - 1
ok : bool = 0
while st <= dr:
    mij = st + (dr - st) // 2
    if L[mij] == x:
        print("Numarul se gaseste in sir")
        ok = 1
        break
    if L[mij] < x:
        st = mij + 1
    else:
        dr = mij - 1
if ok == 0:
    print("Numarul nu se gaseste in sir")

"""Problema 6"""

# Problema 6

sir = input("Propozitie:\n")
lista = sir.split(" ")
suma = 0
index = 0
for i in lista:
    if i.startswith("RON") or i.endswith("RON"):
        suma += int(lista[index-1])
    index += 1
print(suma)



